// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmTMFiEEiFxkXL-P9G00IF99aMp8gCeu4',
    appId: '1:86977094632:web:ca02849987d95344e27a5d',
    messagingSenderId: '86977094632',
    projectId: 'hospitalmanagementflutter',
    authDomain: 'hospitalmanagementflutter.firebaseapp.com',
    storageBucket: 'hospitalmanagementflutter.firebasestorage.app',
    measurementId: 'G-VLWM24H3XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjjniWbiTmBMz97-Au-boPEdvfRgP7TUk',
    appId: '1:86977094632:android:7c3d99770094643ce27a5d',
    messagingSenderId: '86977094632',
    projectId: 'hospitalmanagementflutter',
    storageBucket: 'hospitalmanagementflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdXD7dAowT9HZwXSrjInFDNr5hRQB69Nw',
    appId: '1:86977094632:ios:86ac18aa18655d75e27a5d',
    messagingSenderId: '86977094632',
    projectId: 'hospitalmanagementflutter',
    storageBucket: 'hospitalmanagementflutter.firebasestorage.app',
    iosBundleId: 'br.com.fiap.hospitalmanagementFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdXD7dAowT9HZwXSrjInFDNr5hRQB69Nw',
    appId: '1:86977094632:ios:86ac18aa18655d75e27a5d',
    messagingSenderId: '86977094632',
    projectId: 'hospitalmanagementflutter',
    storageBucket: 'hospitalmanagementflutter.firebasestorage.app',
    iosBundleId: 'br.com.fiap.hospitalmanagementFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmTMFiEEiFxkXL-P9G00IF99aMp8gCeu4',
    appId: '1:86977094632:web:d595e70dd7c1663ee27a5d',
    messagingSenderId: '86977094632',
    projectId: 'hospitalmanagementflutter',
    authDomain: 'hospitalmanagementflutter.firebaseapp.com',
    storageBucket: 'hospitalmanagementflutter.firebasestorage.app',
    measurementId: 'G-7DL7J747C8',
  );
}
